name: HNLib
version: '0.0.1'
main: Heyblock0712.hNLib.HNLib
api-version: '1.21'
authors: [ HN ]
description: is MinecraftHUD WAILA

commands:
  hnlib:
    description: HNLib 庫相關系列指令
    usage: /hnlib
